quiz-game/src/App.jsx, quiz-game/src/firebase/auth.jsx, quiz-game/src/firebase/db.jsx, quiz-game/src/firebase/firebase.jsx, quiz-game/src/firebase/index.jsx
[Closes Issue #11 ](url)
[Closes Issue #6 ](url)
[Closes Issues #7 ](url)
=> Firebase Configuration

quiz-game/src/Components/withAuthorization.jsx
A key value stored in browser application to check if the user is logged in or not which allows multi user functionality by conditionally allowing user only if user is logged in.
=> close issue#36

quiz-game/src/Account.jsx, quiz-game/src/Components/AuthUserContext.jsx, quiz-game/src/Components/withAuthentication.jsx
Adding file to pass down authenticated users to program.
=> close issue#37

quiz-game/src/App.jsx, quiz-game/src/Components/PasswordChange.jsx
Password change code snippet is added
=> Close issue#40

quiz-game/src/App.jsx, quiz-game/src/Components/Landing.css, quiz-game/src/Components/Landing.jsx, quiz-game/src/constants/routes.jsx
Created landing page layout and styles for it.
=> Landing page layout

quiz-game/src/App.jsx, quiz-game/src/Components/Navbar.css, quiz-game/src/Components/Navbar.jsx
Created a navigation bar using reactJS & styled-components
=> React Nav Bar

quiz-game/src/Components/SignOut.jsx
Added a sign out functionality page.
=> Close issue30

quiz-game/src/Components/Faculty/ResultGraph.jsx
Added Result graph functionality.
=> Close issue#53

quiz-game/src/Components/Faculty/AddQuiz.jsx, quiz-game/src/Components/Faculty/ResultGraph.jsx
Added the new title functionality.
=> Close Issue#51

quiz-game/src/Components/Faculty/FacultyHome.jsx
Functionality to disable or enable quiz is added in admin portal. 
Close issue#54
=> Added disable quiz functionality in admin Portal 

quiz-game/src/App.jsx, quiz-game/src/Components/SignUp.jsx, quiz-game/src/constants/routes.jsx
[Fixed Issue #31 ](url)
- Created web page that allows user to signup
=> Closes issue #31

quiz-game/src/App.jsx, quiz-game/src/Components/Account.jsx, quiz-game/src/constants/routes.jsx
authUser is passed down via Context API (It is set at withAuthentication.js file)
=> Created authorization for account 

quiz-game/src/Components/Faculty/AddQuiz.css, quiz-game/src/Components/Faculty/AddQuiz.jsx
=> Added quiz

quiz-game/src/Components/Faculty/FacultyHome.jsx
Added the page which displays the list of quizzes
=> Close issue#18

quiz-game/src/App.jsx, quiz-game/src/Components/E404.jsx
[Fixed Issue #49 ](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/issues/49)
- As a developer i added a feature of error display message while entering wrong credentials by user.
=> Display error message

quiz-game/src/App.jsx, quiz-game/src/Components/Faculty/AddQuiz.jsx, quiz-game/src/constants/routes.jsx
[Fixed Issue #50 ](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/issues/50)
- As a developer i have added a new quiz button in the faculty part by this the admin can create new quizzes.
=> Added new quiz

quiz-game/src/Components/Faculty/EditQuiz.css
[Fixed issue #67 ](https://github.com/WSUCEG-7140/Team-Rainbow--Quiz-Game-App/issues/67)
- As a developer, I added CSS to customize the look and feel of the quiz. 
- I was able to create a consistent design across all the questions and answers to make the quiz look professional and visually appealing. 
- I also added hover effects to certain elements to make the quiz more interactive and engaging for users.
=> Added styles for edit quiz

quiz-game/src/Components/_tests_/AddQuiz.test.jsx
- Adding unit tests for the AddQuiz functionality will be valuable in ensuring that the application is running as expected. 
- Furthermore, unit tests provide an easy way to check that any new code changes do not have unintended consequences.
=> Added testing for add_quiz

quiz-game/src/Components/E404.test.jsx
Added Unit testing for Error handling. it is needed to check if the actual is meeting the expected requirement
=> Close issue#89

quiz-game/src/Components/Faculty/FacultyHome.css
- I've added basic styles to the faculty home page. Let me know if you need any changes or adjustments. Thanks!
=> Added styles to Faculty Home

quiz-game/src/Components/SignUp.test.jsx
- I've completed the unit tests for the sign up feature. Please check the tests to make sure they are working correctly before merging. Thanks!
=> testing for signup

quiz-game/package-lock.json, quiz-game/package.json, quiz-game/src/Components/SignIn.test.jsx, quiz-game/yarn.lock
- I've added unit tests for the sign in feature. Please let me know if there are any issues. Thanks!
=> unit testing for signin
